### PR TITLE
Avoid duplicate reentryConductivity

### PR DESCRIPTION
**Pull request by Gordon-Dry**

### CODE REVIEW

**Review by Starwaster — CHANGES_REQUESTED** [review]
Can't accept this pull request with the change to TaurusHCV because the original TaurusHCV is still in the wild.

Fix this by prepending % to reentryConductivity. (you may also do the same to the other fields affecting loss and pyrolysis)

**Comment by Gordon-Dry** [comment]
I don't understand what you mean wth "still in the wild" and how it creates a problem with a fix inside a patch.

**Comment by Gordon-Dry** [comment]
Here is a screenshot of the difference (left side is the fixed version)
Screen-2021-12-02_15-56-17
:

**Comment by Starwaster** [comment]
Oh, I thought this was the DRE Taurus patch was having an issue with LinuxGuruGamer's re-release of the Taurus which also makes changes to the heat shield

**Pull request merged**
